# Generated by Django 4.1.5 on 2023-03-23 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sorter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("assessment_size", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="studio",
            name="assessment_size",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studio",
            name="current_rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.CreateModel(
            name="Influence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=200)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncentiveProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contribution_factor",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("grade", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
