# Generated by Django 4.1.5 on 2023-03-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ios", "0002_sorter_studio_assessment_size_studio_current_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incentiveproof",
            name="studio",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="ios.studio"
            ),
            preserve_default=False,
        ),
    ]
