# Generated by Django 4.1.5 on 2023-03-23 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ios", "0003_incentiveproof_studio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incentiveproof",
            name="studio",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="ios.studio"
            ),
        ),
    ]
