# Generated by Django 4.1.5 on 2023-03-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ios", "0004_alter_incentiveproof_studio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incentiveproof",
            name="grade",
            field=models.IntegerField(default=0),
        ),
    ]
