# Generated by Django 4.1.5 on 2023-03-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ios", "0005_alter_incentiveproof_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studio",
            name="description",
            field=models.TextField(),
        ),
    ]
